### ISSUE TITLE
small typos

### ISSUE THREAD

**Issue by casare** [kren1/tosheets#3]
Great idea! Thanks!

I just noticed 2 things:
- Would`nt it be "stdout" instead stdin?
- echo '1 2\n3 4' will send exactly this text to the spreadsheet, you need the echo -e option, so the shell can understand that \n is a new line special char.

**Comment by kren1** [comment]
* I see what you mean by using stdout, but I think stdin is bettter, for the case where you don't have a pipe (ie. `tosheets < data.txt`).
* Good catch, tcsh has a builtin echo, so it worked for me, but I'll change it, thanks.
