### ISSUE TITLE
Convenience:  parse spreadsheet id from URL

### ISSUE THREAD

**Issue by erikcw** [kren1/tosheets#6]
Would be really handy for the more lazy among us to automatically parse the spreadsheet id if the full spreadsheet url is passed to `--spreadsheet https://docs.google.com/spreadsheets/d/1kLjuks5YL_ZY1hrRbDm_3jdjdjdd/edit#gid=0`

**Comment by kren1** [comment]
Cool idea! 

Patches are welcome.

**Comment by kren1** [comment]
Implmented by #7 and pushed to pypy. All thanks to @Khoyo
