### ISSUE TITLE
upload as 'Plain Text' even if it looks like number

### ISSUE THREAD

**Issue by avilella** [kren1/tosheets#9]
Hi,

I have a table where column 1 looks like:
```
00001234,12345678
00001235,12345678
```
And I am uploading this to a google sheet which has column 1 formatted as 'Plain Text'.

When I upload it with tosheets, the leading zeros disappear, and turn into:
```
1234,12345678
1235,12345678
```
Anything I can do to avoid that and preserve the values?

**Comment by kren1** [comment]
As a qucik hack and if you don't mind seeing quotes in google sheets , wrapping your numbers in quotes could work. Or anything that makes python's `float("0000123.455")` fail.

 Otherwise if you want to introduce an option that doesn't do the conversion, I would be happy to accept that PR.

**Comment by kren1** [comment]
The #10 should now be released addressing this issue. Thanks again for the patch. I'm closing, but le me know if there are further issues.
